language: node_js
node_js:
  - 8
before_deploy:
  - NODE_ENV=production npm run build
env:
  global:
    - GITHUB_REPO: vkbansal/vkbansal.me
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: aws-website-my-website-mr5h4
  local-dir: public
  skip_cleanup: true
  default_text_charset: 'utf-8'
  on:
    branch: master
    repo: vkbansal/vkbansal.me
