[build]
    command = "yarn build"
    publish = "public"

[build.environment]
    NODE_VERSION = "v11.13.0"

[[redirects]]
    from = "/sqlite-wasm-demo/*"
    to = "https://vkbansal.github.io/sqlite-wasm-demo/:splat"
    status = 200
    force = true
