---
homepage:
    postsLimit: 5

blog:
    prefix: blog
    postsLimit: 5
    pagination: true
    labelSuffix: label/:label
    paginationSuffix: page/:num

author:
    name: Vivek Kumar Bansal
    email: contact@vkbansal.me
    website: https://vkbansal.me

disqus:
    shortname: vkbansal

ga:
    token: UA-54521168-1

social: !!pairs
    - rss:
        name: RSS
        link: http://feeds.feedburner.com/vkbansal
        follow: true
        footer: true
    - twitter:
        name: Twitter
        link: http://twitter.com/_vkbansal
        username: _vkbansal
        follow: true
        footer: true
        share: true
    - github:
        name: Github
        link: https://github.com/vkbansal
        username: vkbansal
        follow: true
        footer: true
    - codepen:
        name: Codepen
        link: http://codepen.io/vkbansal/
        footer: true
    - facebook:
        name: Facebook
        share: true
    - linkedin:
        name: Linkend In
        link: https://in.linkedin.com/in/vkbansal03
        share: true
    - googlePlus:
        name: Google Plus
        share: true
    - npm:
        name: Node Package Manager (NPM)
        link: https://www.npmjs.com/~vkbansal

